# Keycloak Admin Client
# These properties are placeholders and should be configured as per environment
# quarkus.keycloak.admin-client.server-url=http://localhost:8081/auth
# quarkus.keycloak.admin-client.realm=quarkus
# quarkus.keycloak.admin-client.client-id=quarkus-app
# quarkus.keycloak.admin-client.grant-type=client_credentials
# quarkus.keycloak.admin-client.client-secret=secret

# Keycloak Dev Services
%dev.quarkus.keycloak.admin-client.server-url=${quarkus.oidc.auth-server-url}
%dev.quarkus.keycloak.admin-client.realm=wandywharang
%dev.quarkus.keycloak.admin-client.client-id=member-service
%dev.quarkus.keycloak.admin-client.grant-type=client_credentials
%dev.quarkus.keycloak.admin-client.client-secret=member-service-secret
%dev.quarkus.keycloak.devservices.realm-path=wandywharang-realm.json
